### 넘파이(Numpy) : 배열(ndarray, n dimension array)
#### 리스트(list): Linked List 구조(불연속), 동작 속도가 느리다, comma로 요소 구별, 서로 다른 자료형 사용가능
#### 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소를 구별, 오직 한 가지 타입만 갖을 수 있다

In [2]:
import numpy as np

# list
list1 = [0,1,2,3,4,5,'hello']
print(list1,type(list1))

# ndarray
a = np.array([0,1,2,3,4,5])
print(a,type(a))
print(a.dtype)   # 요소의 자료형 int32(windows) , int64(Mac/Linux)
a                # Shift + Tab : 변수위에 커서를 놓고 함수(메서드)의 프로토 타입을 볼수 있다

[0, 1, 2, 3, 4, 5, 'hello'] <class 'list'>
[0 1 2 3 4 5] <class 'numpy.ndarray'>
int32


array([0, 1, 2, 3, 4, 5])

In [4]:
# numpy 의 dtype 객체의 종류 : 대소문자 모두 사용 가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'ulong', 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'b1', 'bool8', 'i8', 'int64', 'u8', 'uint64', 'f2', 'float16', 'f4', 'float32', 'f8', 'float64', 'c8', 'complex64', 'c16', 'complex128', 'object0', 'bytes0', 'str0', 'void0', 'M8', 'datetime64', 'm8', 'timedelta64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'object', 'str', 'bytes', 'a', 'int0', 'uint0'])

### 차원(Dimension,Rank) 과 Shape
#### * 차원(Dimension,Rank)  : 1,2,3차원,n차원, 첫 데이터까지의 대괄호의 갯수
#### * Shape : 차원의 각 축의 요소의 수, 튜플 형식
####  1 차원 Shape : (x,), 벡터(vector)
####  2 차원 Shape : (x,y), 행렬(matrix)
####  3 차원 Shape : (x,y,z) , (면,행,열) 
... 
####  n 차원 Shape : (x,y,z,....)

In [22]:
# 1차원 배열의 shape : (x,)
# np.arange(start,end+1,step)
a = np.arange(12)
print(a,a.dtype)
print(a.ndim, a.shape)  # 1차원 ,(12,)
t = a.shape
print(type(t))
print(a.shape[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11] int32
1 (12,)
<class 'tuple'>
12


In [28]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis=0)과 열(column,세로,수평,axis=1) => 필수암기 
m = np.array([[0,1,2],
              [0,1,2]])
print(m,m.shape)   # (2,3)

m = np.array([[0,1],
              [3,4],
              [5,6]])
print(m,m.shape)  
print(m.shape[0])
print(m.shape[1])

[[0 1 2]
 [0 1 2]] (2, 3)
[[0 1]
 [3 4]
 [5 6]] (3, 2)
3
2


In [33]:
# 3차원 배열의 Shape: (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m,m.shape)

m = np.array([[[0, 1],
               [2, 3]],
              [[4, 5],
               [0, 1]],
              [[2, 3],
               [4, 5]]])
print(m,m.shape)
print(m.shape[0],m.shape[1],m.shape[2],m.shape[-1])

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]] (2, 2, 3)
[[[0 1]
  [2 3]]

 [[4 5]
  [0 1]]

 [[2 3]
  [4 5]]] (3, 2, 2)
3 2 2 2


In [40]:
# shape 바꾸기 함수 : reshape()
m1 = np.arange(12)
print(m1,m1.shape)  # (12,) , 1차원

m2 = m1.reshape(3,4)
print(m2,m2.shape)  # (3, 4) , 2차원

m3 = m1.reshape(2,2,3)  # (2, 2, 3) , 3차원
print(m3,m3.shape)

m2 = m1.reshape(12,1)
print(m2,m2.shape)  # (12, 1) , 2차원

m3 = m1.reshape(12,1,1)
print(m3,m3.shape)  # (12, 1, 1) , 3차원

m2 = m1.reshape(1,12)
print(m2,m2.shape)  # (1,12) , 2차원

m3 = m1.reshape(1,1,12)
print(m3,m3.shape)  # (1,1,12) , 3차원

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] (12, 1)
[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]] (12, 1, 1)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]] (1, 12)
[[[ 0  1  2  3  4  5  6  7  8  9 10 11]]] (1, 1, 12)


### 배열의 인덱싱과 슬라이싱

In [41]:
# 1차원 배열의 인덱싱과 슬라이싱 : list 와 동일한 방법

In [70]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)

# indexing
print(d[0][0]) # 0
print(d[0,0])  # 0, 파이썬 스타일
print(d[2,1])  # 9

# slicing
print(d[0])
print(d[0,:])
print(d[:,0])

print(d[:,:-1])  # 마지막 열을 제외
print(d[:,-1:])  # 마지막 열만 추출, 2차원 유지
print(d[:,[-1]]) # 마지막 열만 추출, 2차원 유지  

d[0,:] = 20      # 0번 행의 모든 요소를 20으로 변경
print(d)

d[::2,::3] = 30  # 슬라이싱 된 요소 전체를 한번에 변경할 수 있다
print(d)

d[:,:] = -1      # 전체 요소를 한번에 변경할 수 있다
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
[0 1 2 3]
[0 1 2 3]
[0 4 8]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 3]
 [ 7]
 [11]]
[[ 3]
 [ 7]
 [11]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [73]:
# 3차원 배열의 인덱싱과 슬라이싱
# data[면,행,열]
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)  # (2, 2, 3)

# indexing
print(d[0][0][0])   # old style
print(d[0,0,0])     # 0
print(d[0,1,2])     # 5

print('-'*30)

# slicing
print(d[:,:-1,:-1])   # (2, 1, 2)
print('-'*30)
print(d[:,1:,1:])     # (2, 1, 2)
print('-'*30)

print(d[:,:,-1])      # (2,2) , 2차원(matrix)
print('-'*30)
print(d[:,-1,-1])     # (2,) , 1차원(vector)

print(d[-1,-1,-1])    # indexing, 11 , scalar

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
0
0
5
------------------------------
[[[0 1]]

 [[6 7]]]
------------------------------
[[[ 4  5]]

 [[10 11]]]
------------------------------
[[ 2  5]
 [ 8 11]]
------------------------------
[[[ 5]]

 [[11]]]
11


### 불린 인덱싱 : 조건식을 사용한 인덱싱, 조건 검색 필터를 사용한 추출(매우 중요)

In [99]:
a = np.array([1,2,3,4,5,6])
print(a)

print(a > 4)
print(a[a > 4])
# print(a[[False, False, False, False, True,True]])

boolean_index = np.array([True,False,True,False,True,True])
print(boolean_index)
print(a[boolean_index])

print(a[a!=3])
print(a[(a > 2) & (a < 6)]) 
print(a[a % 2 == 0])
print(a[a < a.mean()])   # 배열 a에서 평균보다 작은 값만 추출

[1 2 3 4 5 6]
[False False False False  True  True]
[5 6]
[ True False  True False  True  True]
[1 3 5 6]
[1 2 4 5 6]
[3 4 5]
[2 4 6]
[1 2 3]


## dot product: 내적 곱셈 ,행렬(matrix)

In [101]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
print(A)    # (2,3)
print(B)    # (3,2)

dot_product = np.dot(A,B)
print(dot_product)

# (2,3) * (3,2) = (2,2)
# (m,n) * (n,l) = (m,l) # 행렬의 내적 곱셈시 shape 공식 ==> 필수 암기 요망!!

#   X    *  W    =   Y
# (10,4) * (a,b) = (10,2)   #  a = 4, b = 2 를 구할 수 있어야 한다
# (768,10)*(a,b) = (768,3)  #  a = 10, b = 3 

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
